### PR TITLE
Feature/dcmfoss 59 -  Capacity Group Details View

### PR DESCRIPTION
**Pull request by Ruskyy**
## Description
This inclued a bugfix, aswell as the capacity group front end, and a lot of CSS and UI funcionalities.

## Pre-review checks

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by carslen** [comment]
@Bailonis please resolve merge conflicts

**Comment by Bailonis** [comment]
@carslen resolved

**Comment by carslen** [comment]
Again conflicting file `FavoriteServiceImpl.java`, please resolve merge conflict.

**Comment by carslen** [comment]
Please resolve merge conflict after merging #19.
We're going to have this issue again and again, until all PRs with the same code snipped changed have been merged one by one.

**Comment by Bailonis** [comment]
@carslen Resolved on this branch, I will check the others

**Pull request merged**
