### PR TITLE
feat: 2nd community days contributions

### PR DESCRIPTION
**Pull request by nitin-vavdiya**
## Description

Initial contribution done with [this PR](https://github.com/eclipse-tractusx/demand-capacity-mgmt/pull/79).

- Increased Deployability
- Fixed error while saving material demand entities
- Author names added
- Resolved netty DNS resolution error for mac 
- TRG 8 will be taken care off with a separate PR into the Upstream Repository.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by stephanbcbauer** [comment]
@nitin-vavdiya  Since you updated the DEPENDENCIES file ... you could also select the checkbox in your description. Same for copyright. Thanks for creating a new PR and getting rid of the 888 commits.

**Review by evegufy — APPROVED** [review]
LGTM, @nitin-vavdiya you can merge yourself, right?

**Comment by nitin-vavdiya** [comment]
> LGTM, @nitin-vavdiya you can merge yourself, right?

No, My GitHub role is not updated yet!

**Comment by stephanbcbauer** [comment]
@nitin-vavdiya thanks, merged it for you.

**Pull request merged**
