### PR TITLE
Chore/update security tooling

### PR DESCRIPTION
**Pull request by the-tatanka**
Add KICS.
Adjusted veracode config. Add frontend for upload.

### CODE REVIEW

**Comment by the-tatanka** [comment]
@Bailonis do you release your containers somewhere? I saw GitHub packages, they seem to be old - no disrespect.

**Comment by the-tatanka** [comment]
@the-tatanka Check uploaded jar of backend

**Review by Bailonis — APPROVED** [review]
Thanks @the-tatanka for the changes.
In a near future I will contact the security team if i have any doubt, so you do not have so much work.

**Comment by the-tatanka** [comment]
No problem - you're welcome

**Comment by Bailonis** [comment]
They are released on ghtr.io, but at the moment I'm changing it to docker.io, because the support team requested

**Review by carslen — APPROVED** [review]

**Comment by carslen** [comment]
@the-tatanka is it ok for you to merge this PR?

**Comment by the-tatanka** [comment]
yes, thanks for reminding me @carslen

**Pull request merged**
