### PR TITLE
Initial contribution

### PR DESCRIPTION
**Pull request by Bailonis**
## Description

Initial contribution to Eclipse Tractus-X

### CODE REVIEW

**Comment by SebastianBezold** [comment]
3rd party library checks for frontend:
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9852
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9853
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9854
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9855
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9856
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9857
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9858
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9859
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9860
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9861
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9862
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9863
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9864
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9865
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9866
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9867

**Comment by SebastianBezold** [comment]
I also ran the automated dash checks for `backend` and `specification`. For both, there is no further investigation required

**Comment by Bailonis** [comment]
So no further investigation required for frontend?

**Comment by SebastianBezold** [comment]
> So no further investigation required for frontend?

I added all the open issues for frontend libs in a previous comment. Please keep track of them, so that in case of any questions from the EF, someone can answer.
If all of the issues are closed and the libraries approved, you need to run the dash license tool again to add the new info to the `DEPENDENCIES_FRONTEND` file

**Comment by SebastianBezold** [comment]
Project content (initial contribution) review ticket: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9868

**Comment by SebastianBezold** [comment]
Hi @Bailonis,

please do not add further changes like with your [last commit ebe6357](https://github.com/eclipse-tractusx/demand-capacity-mgmt/pull/6/commits/ebe635748f2e5279c2c49a2d58a49ea263c5e725)  to this PR unless required to fix a finding.
The initial contribution check done by the EF is closed. Did you check if all the 3rd party issues are resolved?
If so, please update the `DEPENDENCIES_FRONTED` as last change to this PR and then we merge it

**Comment by Bailonis** [comment]
Hi @SebastianBezold,

Sorry about the commit, I just added a folder named docs, to be according the TGRs 
About the 3rd party issues, we are still waiting for review

**Comment by SebastianBezold** [comment]
> Hi @SebastianBezold,
> 
> Sorry about the commit, I just added a folder named docs, to be according the TGRs About the 3rd party issues, we are still waiting for review

No worries this time. I saw the change and it is ok, but we should keep this PR as it is, so the project content review did actually check the PR content and not just a subset. The check is not triggered again if there are more commits.

You can fix all the TRG related issues after this PR is merge as separate follow-up PRs. Like one PR per TRG for example.

**Comment by Bailonis** [comment]
Hi @SebastianBezold, I have just push an update from the DEPENDENCIES_FRONTED file, hope it is all good!

**Comment by SebastianBezold** [comment]
Initial contribution looks good to me now. Merging it 🚀

**Pull request merged**
