### PR TITLE
Issue cleanup packages manager lockfiles

### LINKED ISSUE #48: Cleanup packages manager lockfiles
## Description

Currently, the repository contains a mixture of package manager lockfiles for its frontend.
This should be fixed, so it becomes clear, which package manager to use

### PR DESCRIPTION
**Pull request by Bailonis**
This PR serves to help keep our project aligned with the TRGs and other open-source policies.

In this case, we have deleted the yarn.lock, and live the package.json

fix #48

### CODE REVIEW

**Comment by SebastianBezold** [comment]
Hi @Bailonis,

this PR does not only include lockfile cleanup. Can you please split the notice file and lock file changes

**Comment by Bailonis** [comment]
Hi @SebastianBezold removed the lock files

**Comment by SebastianBezold** [comment]
Hi @Bailonis,

I can merge it like that, but I would suggest to clean your history. Adding files and then removing them with 2 separate commits in the history just does not look nice. It is also unecessary

**Comment by Bailonis** [comment]
How can I do that??

**Review by SebastianBezold — APPROVED** [review]

**Comment by SebastianBezold** [comment]
Merging like it is. If there will be time after the cleanup, we can maybe go through git commands needed for that

**Pull request merged**
