### PR TITLE
DCMFOSS/72_Keycloak_integration_fixed

### PR DESCRIPTION
**Pull request by Diogo12246**
fixed 72 issues of last PR

- added keycloak as token and session manager
- added login page
- added back-end keycloak integration
- added user entity
- added login and logout functionality

### CODE REVIEW

**Review by carslen — CHANGES_REQUESTED** [review]
Please update `DEPENDENCIES_FRONTEND`and `DEPENDENCIES_BACKEND` file.

Afterwards I'm going to
- open IP review tickets for expected restricted dependencies
- to ask you to recreate the dependencies files once again, with the result that the restricted deps will have a ticketnumber of the IP review tickets
- open IP Check for this PR as it is way to big with more than 10k changed lines of code ([hint 1](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-03/), [hint 2](https://www.eclipse.org/projects/handbook/#ip-project-content))

⚠️ Please avoid such big PRs, slice it into smaller ones to avoid opening IP checks, which takes some time (default 2 weeks).

**Comment by carslen** [comment]
Again conflicting file `FavoriteServiceImpl.java`, please resolve merge conflict.

**Review by Bailonis — APPROVED** [review]
Have been talking with @Diogo12246 and the rest of the team, we think it is all good.
But from beeing a long pr, it will need to do a IP request.

**Comment by Bailonis** [comment]
@carslen can you have a look pls?

**Comment by carslen** [comment]
Created IP-Check at Eclipse Foundation: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10908

**Comment by Bailonis** [comment]
@carslen resolved

**Comment by carslen** [comment]
IP-Check still ongoing.

**Comment by carslen** [comment]
Pinged the IP team as today is due date for the IP check.

**Comment by carslen** [comment]
IP Check approved and closed. Ready for approval and merge.

**Review by carslen — APPROVED** [review]

**Pull request merged**
