### PR TITLE
DEMO_BRANCH

### PR DESCRIPTION
**Pull request by Diogo12246**
## Description

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by carslen** [comment]
Some first remarks on this PR:
- Please add a description to the PR (use edit to add)
- 2 PR checks fail, please check
- Avoid this kind of huge PRs, I've to open a IP-Check for PRs with more than 1000 lines of changed code. IP-Check takes up to 2 weeks.
- It is strongly recommended to create more often PRs to upstream to get the PRs smaller.
- Don't mix topics, e.g changes to the source Code + GH workflows. Do it in seperate PRs

**Comment by Bailonis** [comment]
Hi there @carslen, this pr is still on draft, that is why we didn't added you as a reviewer.

**Comment by carslen** [comment]
> Hi there @carslen, this pr is still on draft, that is why we didn't added you as a reviewer.

If it's on draft, then please mark the PR as draft.

**Comment by Bailonis** [comment]
> If it's on draft, then please mark the PR as draft.

It says I need admin permissions

image

**Comment by carslen** [comment]
I've marked this PR as draft.

As it turns out that this PR will get a big one again, I'll open annother IP-Check for this PR due to the huge amount of changed code. At some point Eclipse-Foundation IP team could get mad about us for opening again and again IP-Checks and we should avoid that.

🚨 For future PRs, please avoid this kind of huge PRs, open smaller PRs but do open PR more often. Do not mix domains in PRs like Documentation, Helm Chart, GH Workflows, source code. For each domain open a seperate PR to upstream.

**Comment by SebastianBezold** [comment]
HI @Bailonis,

what do you mean with "retrive"? Setting it to "ready for review"? I think this should be done by @Diogo12246 as the creator of the PR. 

But a note before doing this. 

- The PR is way to big to review. Please split this to smaller PRs and drop this one here
- Provide e a meaningful PR title
- Provide description of the changes and their effects done

**Comment by SebastianBezold** [comment]
There are still more commits, even though I already commented, that this won't be merged like this. I'll close the PR to not give further impression, that this is an acceptable PR

**Comment by Diogo12246** [comment]
> There are still more commits, even though I already commented, that this won't be merged like this. I'll close the PR to not give further impression, that this is an acceptable PR

It was a mistake on my behalf hence the revert commit. But the branch is done, no more changes will be added here.

**Pull request closed without merging**
