### PR TITLE
DEMO_BRANCH

### PR DESCRIPTION
**Pull request by Diogo12246**
## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by SebastianBezold** [comment]
Hey guys, sorry to say, but what is going on here.
See my comments on #33. 

I was asking for small PRs and proper descriptions. 
Now you opened a new PR, with exactly the same title, still no description and exactly the same branch and commit log

Please take my comments seriously and improve your work. 
We won't accept these kind of contributions

**Comment by Siegfriedk** [comment]
@Diogo12246 please be aware that what @SebastianBezold wrote is exactly what i would have written. 

In OpenSource, this PR is basically a slap in the face for anyone who needs to review 187 commits. 

Do you need onboarding support on how to work in OpenSource?

**Comment by Diogo12246** [comment]
@SebastianBezold  

Hello Sebastian, my understanding (incorrect one it seems) was that you wished for us to open a PR with no additional changes or mistaken commits. Sorry for the misunderstanding. 

Regarding the branch itself @Siegfriedk 

It is a compilation of all the features done to present at the tech demo of DCMFOSS all in one branch. 
Having to go back and break this PR into a lot of chunks and prs will be time consuming on schedule. 
Is there any way we could merge this PR without breaking off to multiple chunks? 
What validations are required? we updated the dependency with the dependency tool. I see there is a error still in front end we will fix it and add it here. 

Thank you in advance

**Comment by Siegfriedk** [comment]
@Diogo12246 you are working under the Eclipse Foundation. Its your duty to read up on how to work in this organization and there is a eclipse handbook.

Mixing and building a huge PR which no one can really review is just a no go.

At least from my point of view i don't have time until in the middle of january for a 'deep review' with you together or something like this.

Its still your best bet to split it up properly and do it right.

**Comment by Diogo12246** [comment]
@Siegfriedk 

Alright! 
Thank you for the clear explanation
We will close this one and discuss with the team to break this into multiple chunks and submit more PRs. 
Expect more PRs to emerge, and of course, please do warn if more and smaller are needed so we can in the team approach this correctly.

Thank you kindly and sorry for any misunderstanding.
Diogo.

**Pull request closed without merging**
