### PR TITLE
Added Chronogram and Demand View Table - 75

### PR DESCRIPTION
**Pull request by Bailonis**
In this PR we added a Chronogram and Demand View Table where we can see everything related with a capacity group, in their details page

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by carslen** [comment]
@Bailonis please resolve merge conflicts

**Comment by Bailonis** [comment]
@carslen Resolved

**Comment by carslen** [comment]
Again conflicting file `FavoriteServiceImpl.java`, please resolve merge conflict.

**Comment by Bailonis** [comment]
Hi there @carslen i have done this to this pr:
image

changed the 53 to 75, this due to I can't resolve this confict:

image

**Comment by carslen** [comment]
Hm, the list of conflicts is increasing instead of decreasing. Please try to resolve. I cannot as I cannot asses the changes. I'm sorry, but we have to go through this merge hell. Also #26 and #28 are affected.

**Comment by Bailonis** [comment]
@carslen I will try but i cannot see the merge conflicts, and that does not help the process

**Comment by Diogo12246** [comment]
Nice.

**Pull request merged**
